FROM ubuntu

RUN apt-get update && apt-get upgrade -y && apt-get install -y python3.7 vim git

CMD bash

#build with: docker build -t python .
#run with: docker run -it python
#once in the terminal, create the file script.py print("Hello World!")
#launch with python3.7 script.py
