FROM ubuntu

RUN apt-get update && apt-get upgrade -y && apt-get install -y ocaml git vim

# docker build -t ocaml .
# docker run --rm -ti ocaml
# vi hello.ml and print_string "Hello World!\n";;
# ocamlc -o hello hello.ml
# ./hello
